name: CI - Testes API Biblioteca

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes REST (Controller)
        run: npm run test-rest-controller
      - name: Rodar testes REST (External)
        run: npm run test-rest-external
      - name: Rodar testes GraphQL (Controller)
        run: npm run test-graphql-controller
